"""Merge Mobile SOS into Incidents for Mission V12

Revision ID: 8c04475d634a
Revises: 9c6346979d57
Create Date: 2026-02-23 22:25:27.185649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c04475d634a'
down_revision: Union[str, Sequence[str], None] = '9c6346979d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_incidents_session_id'), 'incidents', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_session_id'), table_name='incidents')
    op.drop_column('incidents', 'is_resolved')
    op.drop_column('incidents', 'session_id')
    # ### end Alembic commands ###
