"""Add coordinates to CrowdLog

Revision ID: ce892ec17406
Revises: f4d7124c5ed7
Create Date: 2026-02-08 21:51:39.341300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce892ec17406'
down_revision: Union[str, Sequence[str], None] = 'f4d7124c5ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crowd_logs', sa.Column('coordinates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crowd_logs', 'coordinates')
    # ### end Alembic commands ###
